title: DC/OS Field Notes
description: Unofficial notes from using DC/OS in the field.
author: Justin Lee
# email: jlee@mesosphere.com

theme: jekyll-theme-cayman
markdown: kramdown

# kramdown:
#   parse_block_html: true